---
- hosts: all
  user: ansible_system
  tasks:
  - name: Setup | create app directory
    ansible.builtin.file:
      path: ~/apps
      state: directory
      owner: ansible_system

  - name: Deployment | copy 
    copy:
      src: "{{ lookup('ansible.builtin.env', 'JENKINS_HOME') }}/workspace/spring-petclinic_assignment2/target/"
      dest: ~/apps/

  - name: Deployment | run app
    shell: "nohup java -Dserver.port=8080 -jar ~/apps/*.jar &"